#!/usr/bin/env bash
# Migrate hardcoded slate/teal/cyan utilities to design-system tokens.
# Order matters: longest/most-specific patterns first.
set -euo pipefail
FILES=$(find src -type f \( -name "*.jsx" -o -name "*.tsx" \))
run() {
  local pattern="$1"
  local replacement="$2"
  for f in $FILES; do
    sed -i "s#${pattern}#${replacement}#g" "$f"
  done
}
run 'bg-slate-955' 'bg-background'
run 'bg-slate-950' 'bg-background'
run 'bg-slate-900' 'bg-card'
run 'bg-slate-850' 'bg-secondary'
run 'bg-slate-855' 'bg-secondary'
run 'bg-slate-800' 'bg-secondary'
run 'bg-slate-750' 'bg-secondary'
run 'bg-slate-700' 'bg-muted'
run 'hover:bg-slate-900' 'hover:bg-card'
run 'hover:bg-slate-855' 'hover:bg-secondary'
run 'hover:bg-slate-850' 'hover:bg-secondary'
run 'hover:bg-slate-800' 'hover:bg-secondary'
run 'hover:bg-slate-750' 'hover:bg-secondary'
run 'bg-teal-300' 'bg-primary'
run 'bg-teal-400' 'bg-primary'
run 'bg-teal-500' 'bg-primary'
run 'bg-teal-600' 'bg-primary'
run 'hover:bg-teal-200' 'hover:bg-primary/90'
run 'hover:bg-teal-300' 'hover:bg-primary/90'
run 'hover:bg-teal-400' 'hover:bg-primary/90'
run 'hover:bg-teal-500' 'hover:bg-primary'
run 'hover:bg-teal-600' 'hover:bg-primary/90'
run 'text-teal-300' 'text-primary'
run 'text-teal-400' 'text-primary'
run 'text-teal-500' 'text-primary'
run 'hover:text-teal-300' 'hover:text-primary'
run 'hover:text-teal-400' 'hover:text-primary'
run 'border-teal-300' 'border-primary'
run 'border-teal-400' 'border-primary'
run 'border-teal-500' 'border-primary'
run 'hover:border-teal-400' 'hover:border-primary'
run 'hover:border-teal-500' 'hover:border-primary'
run 'divide-teal-400' 'divide-border'
run 'divide-teal-500' 'divide-border'
run 'ring-teal-400' 'ring-primary'
run 'ring-teal-500' 'ring-primary'
run 'shadow-teal-400' 'shadow-primary'
run 'shadow-teal-500' 'shadow-primary'
run 'from-teal-400' 'from-brand-from'
run 'to-teal-400' 'to-brand-from'
run 'from-cyan-400' 'from-brand-to'
run 'from-cyan-500' 'from-brand-to'
run 'from-cyan-600' 'from-brand-to'
run 'to-cyan-400' 'to-brand-to'
run 'to-cyan-500' 'to-brand-to'
run 'to-cyan-600' 'to-brand-to'
run 'bg-cyan-500' 'bg-chart-2'
run 'text-cyan-400' 'text-chart-2'
run 'text-slate-100' 'text-fg-strong'
run 'text-slate-200' 'text-fg-body'
run 'text-slate-250' 'text-fg-body'
run 'text-slate-300' 'text-fg-body'
run 'text-slate-350' 'text-fg-body'
run 'text-slate-400' 'text-fg-muted'
run 'text-slate-450' 'text-fg-muted'
run 'text-slate-500' 'text-fg-subtle'
run 'text-slate-505' 'text-fg-subtle'
run 'text-slate-600' 'text-fg-faint'
run 'text-slate-700' 'text-fg-faint'
run 'text-white' 'text-fg-strong'
run 'hover:text-slate-100' 'hover:text-fg-strong'
run 'hover:text-white' 'hover:text-fg-strong'
run 'hover:text-slate-200' 'hover:text-fg-body'
run 'hover:text-slate-300' 'hover:text-fg-body'
run 'border-slate-900' 'border-border'
run 'border-slate-850' 'border-border'
run 'border-slate-855' 'border-border'
run 'border-slate-800' 'border-border'
run 'border-slate-700' 'border-border-strong'
run 'border-slate-600' 'border-border-emphasis'
run 'divide-slate-900' 'divide-border'
run 'divide-slate-800' 'divide-border'
run 'divide-slate-850' 'divide-border'
echo "Done. Files touched:"
git diff --stat --no-color | tail -25
